import { blocks, command, domainQuery, edit, id, nullableText, object, revision, text, uuid, type ManorTool, type ToolSchema } from './toolDefinitions.ts'

const format: ToolSchema = { type: 'string', enum: ['block_json'] }
const mediaBlock: ToolSchema = { type: 'object', additionalProperties: true }

/** Native block JSON preserves custom blocks and immutable attachment references. */
export const notesTools: readonly ManorTool[] = [
  domainQuery('find_in_note', 'manor_notes_tool_query', 'Find literal case-insensitive text in a committed note’s recursive block JSON, including properties. Returns matching blocks without child duplication, stable block IDs, revision, and pagination.', { id, search: { type: 'string', minLength: 1, maxLength: 500 }, limit: { type: 'integer', minimum: 1, maximum: 200 }, cursor: id }, ['id', 'search', 'limit']),
  domainQuery('export_note', 'manor_notes_tool_query', 'Export one committed note losslessly as native block_json, including title and immutable attachment URLs. Binary file bytes are downloaded separately. Markdown is not supported.', { id, format }, ['id', 'format']),
  domainQuery('get_file_status', 'manor_notes_tool_query', 'Read allocated or ready status for one available account-owned file, including exact size and finalization time. Purging files and unavailable parent notes are excluded.', { id: uuid }, ['id']),
  command('import_note', 'Create a note from native block_json. Preserve all recursive block properties and stable IDs. Existing attachment URLs must identify ready owned files on available notes. Upload new files before referencing them. Markdown is not supported.', { ...edit, format, title: text, folder_id: nullableText, parent_page_id: nullableText, content_json: blocks }, ['id', 'expected_revision', 'format', 'title', 'folder_id', 'parent_page_id', 'content_json']),
  { name: 'import_markdown_note', description: 'Create a note from Markdown, or replace an existing note’s title and content from Markdown, converted on the server into native blocks (headings, lists, tasks, quotes, code, tables, math, dividers, links, images, files). A document that opens with a level-one heading is titled by it and the heading leaves the body; title is the fallback for documents without one. expected_revision 0 creates the note at id; the current revision replaces it. Images and file links with local paths need uploaded files: pass assets mapping each path as written (or its file name) to a ready manor-attachment:// URL. The receipt lists unmapped assets with the empty block awaiting each, so the usual flow is import once, upload the listed files with parent_id set to this note, then import again with assets at the returned revision. Front matter is removed and returned.', inputSchema: object({ command_id: uuid, ...edit, title: text, folder_id: nullableText, parent_page_id: nullableText, markdown: { type: 'string', maxLength: 4000000 }, assets: { type: 'object', additionalProperties: true } }, ['command_id', 'id', 'expected_revision', 'markdown']), execution: { kind: 'markdown' }, readOnly: false },
  command('duplicate_note', 'Duplicate a note and its available descendants atomically (maximum 100 notes). Copies receive fresh block IDs and share immutable attachments; the source remains unchanged. Supply the root source revision, a new root ID, and destination hierarchy.', { ...edit, new_id: id, title: text, folder_id: nullableText, parent_page_id: nullableText }, ['id', 'expected_revision', 'new_id', 'title', 'folder_id', 'parent_page_id']),
  command('duplicate_note_blocks', 'Append copies of 1 to 50 selected blocks with their nested children to a target note, using fresh recursive block IDs and unchanged immutable attachments. Supply both revisions; the same note may be source and target.', { ...edit, target_note_id: id, target_expected_revision: revision, block_ids: { type: 'array', minItems: 1, maxItems: 50, items: id } }, ['id', 'expected_revision', 'target_note_id', 'target_expected_revision', 'block_ids']),
  command('remove_empty_note_folder', 'Remove a folder only when no notes (including Trash) or live child folders refer to it. Never lifts or relocates contents.', edit, ['id', 'expected_revision']),
  command('edit_note_media', 'Insert or replace up to 100 precise native image, audio, video, or file blocks. Supply full block properties and a ready owned manor-attachment:// URL. A replacement preserves the existing block ID and changes the file reference without overwriting immutable bytes. Unrelated blocks are preserved.', { ...edit, edits: { type: 'array', minItems: 1, maxItems: 100, items: object({ kind: { type: 'string', enum: ['replace', 'insert_before', 'insert_after', 'append'] }, block_id: id, block: mediaBlock }, ['kind', 'block']) } }, ['id', 'expected_revision', 'edits']),
]
