import { batch, command, date, edit, id, object, paging, period, domainQuery, revision, timestamp, uuid, type ManorTool } from './toolDefinitions.ts'

const workspacePaging = { limit: paging.limit, cursor: { type: 'string', minLength: 1, maxLength: 4096 } as const }

export const workspaceTools: readonly ManorTool[] = [
  domainQuery('get_application_history', 'manor_workspace_query', 'Read retained application stage transitions with stable IDs and timestamps, bounded by application and optional timestamp range.', { ...workspacePaging, application_id: id, from: timestamp, to: timestamp }, ['application_id']),
  domainQuery('list_trash', 'manor_workspace_query', 'List trashed tasks, applications and Notes metadata with revision, purge eligibility and recoverability. No document bodies are returned.', { ...workspacePaging, module: { type: 'string', enum: ['tasks', 'applications', 'notes'] } }, []),
  domainQuery('get_workspace_context', 'manor_workspace_query', 'Read saved account timezone, local date, capability version and access restrictions. Live selection and unsaved browser drafts are unavailable here.', {}, []),
  domainQuery('get_day_overview', 'manor_workspace_query', 'Read bounded task, calendar and scratch-block lists, daily ratings and aggregate counts for a saved-timezone date. Each list has its own continuation cursor.', { date, limit: paging.limit }, ['date']),
  domainQuery('query_calendar_events', 'manor_workspace_query', 'Read synchronized events from enabled calendars overlapping an inclusive saved-timezone date range, at most 366 days. Includes all-day events; no Google writes.', { ...workspacePaging, ...period, account_id: id, calendar_id: id }, ['from', 'to']),
  domainQuery('query_habits', 'manor_workspace_query', 'Read habit definitions, revisions and effective status on a date. Retired habits and their history remain available.', { ...workspacePaging, date, status: { type: 'string', enum: ['active', 'paused', 'retired'] } }, []),
  domainQuery('query_habit_history', 'manor_workspace_query', 'Read bounded eligible tracked habit-days, including missing entries and revisions, over at most 366 days. Paused, retired, pre-creation and future days are excluded.', { ...workspacePaging, ...period, habit_id: id }, ['from', 'to']),
  domainQuery('get_metrics', 'manor_workspace_query', 'Aggregate up to 366 inclusive account-local dates. Task completions use current completed_at timestamps; habits use eligible tracked-day denominators; Mood and Focus include categorical samples and missingness. Future days are excluded.', { ...period, group_by: { type: 'string', enum: ['total', 'day'] } }, ['from', 'to', 'group_by']),
  domainQuery('get_operation_status', 'manor_workspace_query', 'Read a committed command receipt’s structural status. A missing receipt means not recorded, not necessarily failed. Never returns stored result content.', { command_id: uuid }, ['command_id']),
  domainQuery('get_changes_since', 'manor_workspace_query', 'Read content-free changes after an account cursor, including physical deletions and purge tombstones. Cursor 0 starts at feed installation; acquire the current cursor before a full initial read. Cursor advances in commit order per account.', { cursor: { type: 'string', pattern: '^[0-9]+$', maxLength: 20 }, limit: paging.limit }, ['cursor']),
  domainQuery('get_background_run', 'manor_workspace_query', 'Read current Google or X synchronization job status. Raw errors, tokens, provider cursors and job payloads are excluded. This is current job state, not historical run retention.', { provider: { type: 'string', enum: ['google', 'x'] }, account_id: id }, ['provider', 'account_id']),
  domainQuery('get_preferences', 'manor_workspace_query', 'Read saved display name, timezone and profile revision. Browser-local appearance settings are not account preferences.', {}, []),
  domainQuery('get_integration_status', 'manor_workspace_query', 'Read safe account-owned Google and X connection metadata and synchronization status, with no credentials or raw errors.', workspacePaging, []),
  command('update_preferences', 'Update only the display name and saved timezone using the current profile revision. Preserves unrelated profile settings.', { expected_revision: revision, name: { type: 'string', minLength: 1, maxLength: 120 }, timezone: { type: 'string', minLength: 1, maxLength: 100 } }, ['expected_revision']),
  command('retry_background_run', 'Reschedule a failed, unleased Google or X synchronization job whose connection still exists. Active or healthy jobs cannot be retried.', { provider: { type: 'string', enum: ['google', 'x'] }, account_id: id }, ['provider', 'account_id']),
  command('save_task_view', 'Create or replace a named saved task filter set at its current revision; revision zero creates it.', { ...edit, name: { type: 'string', minLength: 1, maxLength: 120 }, rules: { type: 'array', maxItems: 30, items: object({ id, property: { type: 'string', enum: ['context', 'status', 'priority', 'due'] }, value: { type: 'string', maxLength: 200 }, operator: { type: 'string', enum: ['on', 'before', 'after', 'within'] }, date, ...period }, ['id', 'property']) } }, ['id', 'expected_revision', 'name', 'rules']),
  command('delete_task_view', 'Remove a saved task filter set at its current revision without changing tasks.', edit, ['id', 'expected_revision']),
  batch('clear_habit_entries', 'clear_habit_entry', 'Clear 1 to 50 dated habit entries for today or yesterday using each entry revision. Preserves habit definitions.', { ...edit, date }, ['id', 'expected_revision', 'date'])
]
