-- Wrap auth.uid() in a subselect so Postgres evaluates it once per statement instead of once per row, and index the policy columns that lacked one.
alter policy alfred_actions_owner on public.alfred_actions using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy alfred_memories_owner on public.alfred_memories using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy workspace_calendar_accounts_owner on public.calendar_accounts using (user_id = (select auth.uid()));
alter policy workspace_calendar_events_owner on public.calendar_events using (user_id = (select auth.uid()));
alter policy workspace_calendars_owner on public.calendars using (user_id = (select auth.uid()));
alter policy contexts_owner on public.contexts using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy habit_entries_owner on public.habit_entries using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy habit_finalized_days_owner on public.habit_finalized_days using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy habit_freeze_grants_owner on public.habit_freeze_grants using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy habit_freeze_intents_owner on public.habit_freeze_intents using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy habit_freeze_usage_owner on public.habit_freeze_usage using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy habit_lifecycle_owner on public.habit_lifecycle using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy habit_month_pools_owner on public.habit_month_pools using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy habits_owner on public.habits using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy job_roles_owner on public.job_roles using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy job_stage_transitions_owner on public.job_stage_transitions using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy kb_entries_owner on public.kb_entries using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy leetcode_attempts_owner on public.leetcode_attempts using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy leetcode_freeze_owner on public.leetcode_freeze_intents using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy leetcode_freeze_read on public.leetcode_freeze_intents using (user_id = (select auth.uid()));
alter policy leetcode_notes_owner on public.leetcode_notes using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy leetcode_problems_owner on public.leetcode_problems using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy mood_focus_entries_owner on public.mood_focus_entries using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy note_attachments_owner on public.note_attachments using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy note_folders_owner on public.note_folders using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy note_pages_owner on public.note_pages using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy profiles_owner on public.profiles using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy links_command on public.record_links using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy resumes_owner on public.resumes using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy saved_task_views_owner on public.saved_task_views using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy scratch_blocks_owner on public.scratch_blocks using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy series_command on public.task_series using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy series_read on public.task_series using (user_id = (select auth.uid()));
alter policy tasks_owner on public.tasks using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy x_connections_owner on public.x_connections using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create index if not exists file_objects_user_id_idx on public.file_objects(user_id);
create index if not exists note_attachments_user_id_idx on public.note_attachments(user_id);
